feat: add stage env to allowed environments for kpis
gjensidige/register-deploy-action pull request #3
Opened 2021-11-15 12:55 UTC by peterD4N

2021-11-15 12:56 UTC, sigurdfalk requested changes
Need to update the `/dist` bundle by running `npm run all`

2021-11-15 13:36 UTC, peterD4N commented
> Need to update the `/dist` bundle by running `npm run all`

Thank you, updated 😉

2021-11-15 13:37 UTC, sigurdfalk commented on src/main.ts
> +const allowedEnvs = ['sand', 'dev', 'test', 'stage', 'prod'];
Not `staging`?

2021-11-15 13:43 UTC, peterD4N commented on src/main.ts
> +const allowedEnvs = ['sand', 'dev', 'test', 'stage', 'prod'];
I was thinking to use staging but then as we use e.g. `test` not `testing` I went for `stage`. But `staging` also works for me.

2021-11-15 13:50 UTC, sivapalan approved these changes

2021-11-15 16:58 UTC, akorp approved these changes

2021-11-16 08:03 UTC, sigurdfalk approved these changes

2021-11-16 08:24 UTC, merged